proxy_groups:
- name: AI
  type: fallback
  members:
  - 🎏JP-TOKYO「NTT🏡」-B
  - 🎏JP-TOKYO「NTT🏡」-D
  - 🎏JP-TOKYO「NTT🏡」-C
  - 🎏JP-TOKYO「NTT🏡」-A
  - 美国ATT-原生家宽-A3
  - 美国ATT-原生家宽-A1
  - 美国ATT-原生家宽-A2
  params:
    url: https://chatgpt.com
    interval: 300
    timeout: 8
- name: 媒体
  type: select
  members:
  - 🚋香港『HKBN🏡』独享2.5G-B
  - 🚋香港『HKBN🏡』独享2.5G-A
  - 🚋香港『HKBN🏡』独享2.5G-C
  - 🚋香港『HKBN🏡』独享2.5G-D
  - 🎏JP-TOKYO「NTT🏡」-B
  - 🎏JP-TOKYO「NTT🏡」-C
  params:
    policy-select-name: 🚋香港『HKBN🏡』独享2.5G-B
- name: Telegram
  type: select
  members:
  - 🚋香港『HKBN🏡』独享2.5G-B
  - 媒体
  - PROXY
  - 香港节点
  - 日本节点
  - 台湾节点
  - 新加坡节点
  - 韩国节点
  - 美国节点
  params:
    policy-select-name: 🚋香港『HKBN🏡』独享2.5G-B
- name: YouTube
  type: select
  members:
  - 媒体
  - PROXY
  - 香港节点
  - 日本节点
  - 台湾节点
  - 新加坡节点
  - 韩国节点
  - 美国节点
  params:
    policy-select-name: 媒体
- name: Netflix
  type: select
  members:
  - PROXY
  - 媒体
  - 香港节点
  - 日本节点
  - 台湾节点
  - 新加坡节点
  - 韩国节点
  - 美国节点
  params:
    policy-select-name: PROXY
- name: Disney+
  type: select
  members:
  - PROXY
  - 媒体
  - 香港节点
  - 日本节点
  - 台湾节点
  - 新加坡节点
  - 韩国节点
  - 美国节点
  params:
    policy-select-name: PROXY
- name: MAX
  type: select
  members:
  - PROXY
  - 媒体
  - 香港节点
  - 日本节点
  - 台湾节点
  - 新加坡节点
  - 韩国节点
  - 美国节点
  params:
    policy-select-name: PROXY
- name: TikTok
  type: select
  members:
  - PROXY
  - 媒体
  - 香港节点
  - 日本节点
  - 台湾节点
  - 新加坡节点
  - 韩国节点
  - 美国节点
  params:
    policy-select-name: PROXY
- name: Spotify
  type: select
  members:
  - PROXY
  - 媒体
  - 香港节点
  - 日本节点
  - 台湾节点
  - 新加坡节点
  - 韩国节点
  - 美国节点
  params:
    policy-select-name: PROXY
- name: 香港节点
  type: url-test
  members: []
  params:
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    timeout: 5
    select: 0
    policy-regex-filter: 🇭🇰|HK|Hong|hong|香港|深港|沪港|京港|港
- name: 台湾节点
  type: url-test
  members: []
  params:
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    timeout: 5
    select: 0
    policy-regex-filter: 🇹🇼|TW|TWN|Taiwan|Taipei|taiwan|台湾|台灣|台北|台中|新北|彰化
- name: 日本节点
  type: url-test
  members: []
  params:
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    timeout: 5
    select: 0
    policy-regex-filter: 🇯🇵|JP|Japan|japan|Tokyo|tokyo|日本|东京|大阪|京日|苏日|沪日|上日|川日|深日|广日
- name: 新加坡节点
  type: url-test
  members: []
  params:
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    timeout: 5
    select: 0
    policy-regex-filter: 🇸🇬|SG|Sing|sing|新加坡|狮城|沪新|京新|深新|杭新|广新
- name: 韩国节点
  type: url-test
  members: []
  params:
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    timeout: 5
    select: 0
    policy-regex-filter: 🇰🇷|KR|Korea|korea|KOR|韩国|首尔|韩|韓|春川
- name: 美国节点
  type: url-test
  members: []
  params:
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    timeout: 5
    select: 0
    policy-regex-filter: 🇺🇸|US|USA|America|america|United States|美国|凤凰城|洛杉矶|西雅图|芝加哥|纽约|沪美
